variables:
  NUGET_PATH: 'C:\Nuget\nuget.exe'
  MSBUILD_PATH: 'D:\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\msbuild.exe'
  ErrorActionPreference: STOP

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - 'dotnet restore'
    - 'dotnet build'
  artifacts:
    expire_in: 1 week
    paths:
      - PerchikSharp\bin\Debug\netcoreapp3.1\*.dll
      - PerchikSharp\bin\Debug\netcoreapp3.1\*.json
      - PerchikSharp\bin\Debug\netcoreapp3.1\*.exe
      - PerchikSharp\bin\Debug\netcoreapp3.1\*.txt
      - PerchikSharp\bin\Debug\netcoreapp3.1\*.mp3
      - PerchikSharp\bin\Debug\netcoreapp3.1\*.jpg
  only:
    - master
    - DeployTest
  tags:
    - powershell
    - windows

deploy:
  stage: deploy
  script:
    - 'C:\Users\buggt\AppData\Local\Programs\Python\Python38-32\python.exe .\deploy.py'
    - 'cd C:\Projects\PersikSharp\Builds'
    - 'PerchikSharp.exe /u'
  only:
    - master
    - DeployTest
  tags:
    - powershell
    - windows
  dependencies:
    - build