
variables:
  EXE_RELEASE_FOLDER: 'PersikSharp\bin\Release'
  DEPLOY_FOLDER: 'C:\Projects\PersikSharp\Builds'
  NUGET_PATH: 'C:\Nuget\nuget.exe'
  MSBUILD_PATH: 'E:\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\msbuild.exe'
  NUNIT_PATH: 'C:\Program Files (x86)\NUnit.org\nunit-console\nunit3-console.exe'


stages:
  - build
  - deploy

build:
  stage: build
  script:
    - '"C:\Nuget\nuget.exe" restore'
    - '"E:\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\msbuild.exe" /p:Configuration=Release'
  artifacts:
    expire_in: 1 week
    paths:
      - PersikSharp\bin\Release\PersikSharp.exe
  tags:
    - powershell
    - windows

deploy:
  stage: deploy
  script:
    - 'xcopy /y ".\PersikSharp\bin\Release\PersikSharp.exe" "C:\Projects\PersikSharp\Builds\"'
    - 'xcopy /y ".\PersikSharp\bin\Release\*.dll" "C:\Projects\PersikSharp\Builds\"'
    - 'xcopy /y ".\PersikSharp\Configs\*" "C:\Projects\PersikSharp\Builds\Configs\"'
    - 'Get-Process | Where-Object {$_.Path -like "C:\Projects\PersikSharp\Builds\PersikSharp.exe"} | Stop-Process -Force -processname {$_.ProcessName}'
    - 'cd  "C:\Projects\PersikSharp\Builds\"'
    - 'start .\PersikSharp.exe'
  tags:
    - powershell
    - windows
  dependencies:
    - build