
variables:
  EXE_RELEASE_FOLDER: 'PersikSharp\bin\Release'
  DEPLOY_FOLDER: 'C:\Projects\PersikSharp\Builds'
  NUGET_PATH: 'C:\Nuget\nuget.exe'
  MSBUILD_PATH: 'D:\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\msbuild.exe'
  ErrorActionPreference: STOP


stages:
  - build
  - deploy

build:
  stage: build
  script:
    - 'dotnet restore'
    - 'dotnet build'
  artifacts:
    expire_in: 1 week
    paths:
      - PerchikSharp\bin\Debug\netcoreapp3.1\*.dll
      - PerchikSharp\bin\Debug\netcoreapp3.1\*.json
  only:
    - master
  tags:
    - powershell
    - windows

deploy:
  stage: deploy
  script:
    - powershell -File .\deploy.ps1
  only:
    - master
  tags:
    - powershell
    - windows
  dependencies:
    - build