
variables:
  EXE_RELEASE_FOLDER: 'PersikSharp\bin\Release'
  DEPLOY_FOLDER: 'C:\Projects\PersikSharp\Builds'
  NUGET_PATH: 'C:\Nuget\nuget.exe'
  MSBUILD_PATH: 'D:\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\msbuild.exe'
  ErrorActionPreference: STOP


stages:
  - build
  - deploy

build:
  stage: build
  script:
    - powershell -Command '"C:\Nuget\nuget.exe" restore'
    - start-process "D:\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\msbuild.exe" "/p:Configuration=Release"
  artifacts:
    expire_in: 1 week
    paths:
      - PersikSharp\bin\Release\PersikSharp.exe
      - PersikSharp\bin\Release\*.dll
  only:
    - master
  tags:
    - powershell
    - windows

deploy:
  stage: deploy
  script:
    - powershell -File .\deploy.ps1
  only:
    - master
  tags:
    - powershell
    - windows
  dependencies:
    - build