//This code was generated by a tool.
//Changes to this file will be lost if the code is regenerated.
// See the blog post here for help on using the generated code: http://erikej.blogspot.dk/2014/10/database-first-with-sqlite-in-universal.html
using SQLite;
using System;
using System.Collections.Generic;
using Telegram.Bot.Types;

namespace PersikSharp
{
    public class SQLiteDb
    {
        SQLiteConnection db;

        public SQLiteDb(string path)
        {
            this.db = new SQLiteConnection(path);
        }
        
         public void Create()
        {
            db.CreateTable<SampleTable>();
            db.CreateTable<Users>();
        }

        public List<Users> GetUsersById(int Id)
        {
            return db.CreateCommand($"select * from Users where Id={Id}").ExecuteQuery<Users>();
        }

        public void InsertUser(User user)
        {
            db.Insert(new Users()
            {
                Id = user.Id,
                FirstName = user.FirstName,
                LastName = user.LastName,
                Username = user.Username
            });
        }

        public void InsertUserIfNotExist(User user)
        {
            var users = GetUsersById(user.Id);
            if (users.Count > 0)
                return;

            InsertUser(user);
        }
        public void RemoveUser(int Id)
        {
            var users = GetUsersById(Id);
            foreach(var user in users)
                db.Delete(user);
        }
    }

    public partial class SampleTable
    {
        [PrimaryKey]
        [MaxLength(10)]
        public String ID { get; set; }
        
        [MaxLength(30)]
        public String name { get; set; }
        
    }
    
    public partial class Users
    {
        [PrimaryKey]
        public Int32 Id { get; set; }
        
        [MaxLength(30)]
        public String FirstName { get; set; }
        
        [MaxLength(30)]
        public String LastName { get; set; }
        
        [MaxLength(30)]
        public String Username { get; set; }
    }
    
}
